({
    appDir: "./",
    baseUrl: "module",
    dir: "../build",
    paths: {
    	jquery        : 'empty:',
        uploadify     : 'empty:',
        chat          : 'empty:',
        kindeditor    : 'empty:',
        bdshare       : 'empty:',
        fullcalendar  : 'empty:',
        fc_zh_cn      : 'empty:',
        datepicker    : 'empty:',
        ZeroClipboard : 'empty:',
        bigColorPicker: 'empty:',
        qrcode        : 'empty:',
        cloudzoom     : 'empty:',
        raty          : 'empty:',
        jcrop         : 'empty:',
        
        indexjs       : 'empty:',
        taskmap       : 'empty:',
        malljs         : 'empty:'
    },
    modules: [
        { name: "aboutPage" },
        { name: "agreementPage"},
        { name: "newsPage"},
        { name: "casePage"},
        { name: "helpPage" },
        { name: "ensurePage"},
        { name: "hirePage"},
        { name: "employerPage"},
        { name: "pagePage"},

        { name: "taskPage"},
        { name: "monthtaskPage"},
        { name: "bussinessPage"},
        { name: "servicePage"},
        { name: "userPage"},
        { name: "userstorePage"},
        { name: "regPage"},
        { name: "loginPage"},
        { name: "orderPage"},
        { name: "publishPage"},
        { name: "tasktoPage"},
        { name: "monthtasktoPage"},
        { name: "freedomtemplatePage"},
        { name: "shopPage"},
        { name: "bbsPage"},
        { name: "indexPage"},
        { name: "taskmapPage"},
        { name: "mallPage"}

    ]
})